export const FETCH_NEWS = 'NEWS/FETCH_NEWS';
export const FETCH_NEWS_SUCCESS = 'NEWS/FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'NEWS/FETCH_NEWS_FAIL';

export const LOAD_NEWS = 'NEWS/LOAD_NEWS';
export const LOAD_NEWS_SUCCESS = 'NEWS/LOAD_NEWS_SUCCESS';
export const LOAD_NEWS_FAIL = 'NEWS/LOAD_NEWS_FAIL';

export const SORT_NEWS = 'NEWS/SORT_NEWS';
export const SORT_NEWS_SUCCESS = 'NEWS/SORT_NEWS_SUCCESS';
// TODO: Он не нужен
// export const SORT_NEWS_FAIL = 'NEWS/SORT_NEWS_FAIL';

export const REFRESH_NEWS = 'NEWS/REFRESH_NEWS';
export const REFRESH_NEWS_SUCCESS = 'NEWS/REFRESH_NEWS_SUCCESS';
export const REFRESH_NEWS_FAIL = 'NEWS/REFRESH_NEWS_FAIL';

export const SHOW_WARNING = 'NEWS/SHOW_WARNING';
export const HIDE_WARNING = 'NEWS/HIDE_WARNING';
