export const FETCH_NEWS = 'NEWS/FETCH_NEWS';
export const FETCH_NEWS_SUCCESS = 'NEWS/FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'NEWS/FETCH_NEWS_FAIL';

export const LOAD_NEWS = 'NEWS/LOAD_NEWS';
export const LOAD_NEWS_SUCCESS = 'NEWS/LOAD_NEWS_SUCCESS';
export const LOAD_NEWS_FAIL = 'NEWS/LOAD_NEWS_FAIL';

export const FILTER_NEWS = 'NEWS/FILTER_NEWS';
export const FILTER_NEWS_SUCCESS = 'NEWS/FILTER_NEWS_SUCCESS';
// export const FILTER_NEWS_FAIL = 'NEWS/FILTER_NEWS_FAIL';

export const HIDE_WARNING = 'NEWS/HIDE_WARNING';

// export const REFRESH_NEWS = 'NEWS/REFRESH_NEWS';
// export const REFRESH_NEWS_SUCCESS = 'NEWS/REFRESH_NEWS_SUCCESS';
// export const REFRESH_NEWS_FAIL = 'NEWS/REFRESH_NEWS_FAIL';

export const TOGGLE_LIKE_NEWS = 'NEWS/TOGGLE_LIKE_NEWS';
